# Generated by Django 5.2.1 on 2026-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('Carnes', 'Carnes'), ('Hamburguesas', 'Hamburguesas'), ('Pastas', 'Pastas'), ('Bebidas', 'Bebidas')], max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('tiempo_preparacion', models.IntegerField(default=15)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('requiere_termino', models.BooleanField(default=False)),
                ('permite_observaciones', models.BooleanField(default=True)),
                ('disponible', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
